import type { Worker, ServiceCategory } from './types';

export const SERVICE_CATEGORIES: {
  name: ServiceCategory;
  icon: string;
  desc: string;
  baseCost: number;
  color: string;
  bg: string;
}[] = [
  { name: 'Plumbing', icon: 'Droplets', desc: 'Pipes, taps, leaks, fittings', baseCost: 89, color: 'text-secondary-600', bg: 'bg-secondary-50' },
  { name: 'Electrical', icon: 'Zap', desc: 'Wiring, switches, repairs', baseCost: 99, color: 'text-accent-600', bg: 'bg-accent-50' },
  { name: 'Carpentry', icon: 'Hammer', desc: 'Furniture, doors, fixtures', baseCost: 129, color: 'text-amber-700', bg: 'bg-amber-50' },
  { name: 'Painting', icon: 'PaintbrushVertical', desc: 'Walls, interiors, exteriors', baseCost: 249, color: 'text-rose-600', bg: 'bg-rose-50' },
  { name: 'Cleaning', icon: 'Sparkles', desc: 'Home, deep, move-in/out', baseCost: 149, color: 'text-primary-600', bg: 'bg-primary-50' },
  { name: 'Gardening', icon: 'Sprout', desc: 'Lawn, plants, landscaping', baseCost: 99, color: 'text-teal-600', bg: 'bg-teal-50' },
  { name: 'Driving', icon: 'Car', desc: 'Commute, errands, delivery', baseCost: 79, color: 'text-indigo-600', bg: 'bg-indigo-50' },
  { name: 'Caregiving', icon: 'HeartHandshake', desc: 'Eldercare, childcare, support', baseCost: 129, color: 'text-pink-600', bg: 'bg-pink-50' },
  { name: 'Technical Services', icon: 'Wrench', desc: 'Appliances, devices, setup', baseCost: 149, color: 'text-slate-700', bg: 'bg-slate-100' },
  { name: 'Househelp', icon: 'Home', desc: 'Cooking, dusting, daily chores', baseCost: 99, color: 'text-orange-600', bg: 'bg-orange-50' },
];

export const WORKERS: Worker[] = [
  {
    id: 'w1',
    name: 'Rajesh Kumar',
    trade: 'Plumbing',
    skills: ['Pipe Repair', 'Tap Fitting', 'Drainage', 'Geyser Install'],
    certifications: ['ITI Plumbing Certified', 'Coop Safety Training'],
    experienceYears: 7,
    distanceKm: 2.1,
    available: true,
    availableNow: true,
    rating: 4.8,
    jobsCompleted: 342,
    currentWorkload: 62,
    recentJobs: 38,
    verified: true,
    cooperative: 'Bharat Seva Cooperative',
    avatarColor: 'bg-primary-600',
    initials: 'RK',
    earningsMonth: 18450,
    welfareContribution: 920,
    coopContribution: 1845,
  },
  {
    id: 'w2',
    name: 'Imran Sheikh',
    trade: 'Plumbing',
    skills: ['Pipe Repair', 'Sanitary Fixtures', 'Leak Detection'],
    certifications: ['ITI Plumbing', 'Advanced Leak Diagnostics'],
    experienceYears: 5,
    distanceKm: 3.4,
    available: true,
    availableNow: true,
    rating: 4.7,
    jobsCompleted: 198,
    currentWorkload: 34,
    recentJobs: 12,
    verified: true,
    cooperative: 'Bharat Seva Cooperative',
    avatarColor: 'bg-secondary-600',
    initials: 'IS',
    earningsMonth: 14200,
    welfareContribution: 710,
    coopContribution: 1420,
  },
  {
    id: 'w3',
    name: 'Sunita Devi',
    trade: 'Cleaning',
    skills: ['Deep Cleaning', 'Kitchen Sanitization', 'Move-in Cleaning'],
    certifications: ['Hygiene Certified', 'Eco-Friendly Practices'],
    experienceYears: 6,
    distanceKm: 1.8,
    available: true,
    availableNow: false,
    rating: 4.9,
    jobsCompleted: 410,
    currentWorkload: 70,
    recentJobs: 44,
    verified: true,
    cooperative: 'Swachh Seva Cooperative',
    avatarColor: 'bg-teal-600',
    initials: 'SD',
    earningsMonth: 19800,
    welfareContribution: 990,
    coopContribution: 1980,
  },
  {
    id: 'w4',
    name: 'Anil Verma',
    trade: 'Electrical',
    skills: ['Wiring', 'Switch Repair', 'Inverter Setup', 'Fan Install'],
    certifications: ['Licensed Electrician', 'Electrical Safety Grade A'],
    experienceYears: 9,
    distanceKm: 2.6,
    available: true,
    availableNow: true,
    rating: 4.8,
    jobsCompleted: 288,
    currentWorkload: 48,
    recentJobs: 22,
    verified: true,
    cooperative: 'Bharat Seva Cooperative',
    avatarColor: 'bg-accent-600',
    initials: 'AV',
    earningsMonth: 21000,
    welfareContribution: 1050,
    coopContribution: 2100,
  },
  {
    id: 'w5',
    name: 'Mohammed Faisal',
    trade: 'Electrical',
    skills: ['Wiring', 'MCB Repair', 'Smart Home Setup'],
    certifications: ['ITI Electrical'],
    experienceYears: 4,
    distanceKm: 4.1,
    available: true,
    availableNow: true,
    rating: 4.6,
    jobsCompleted: 142,
    currentWorkload: 22,
    recentJobs: 8,
    verified: true,
    cooperative: 'Bharat Seva Cooperative',
    avatarColor: 'bg-amber-600',
    initials: 'MF',
    earningsMonth: 11800,
    welfareContribution: 590,
    coopContribution: 1180,
  },
  {
    id: 'w6',
    name: 'Prakash Rao',
    trade: 'Carpentry',
    skills: ['Furniture Repair', 'Door Fitting', 'Modular Work'],
    certifications: ['Master Carpenter', 'Furniture Design Cert.'],
    experienceYears: 11,
    distanceKm: 3.0,
    available: true,
    availableNow: false,
    rating: 4.9,
    jobsCompleted: 356,
    currentWorkload: 58,
    recentJobs: 30,
    verified: true,
    cooperative: 'Kushal Seva Cooperative',
    avatarColor: 'bg-rose-600',
    initials: 'PR',
    earningsMonth: 22500,
    welfareContribution: 1125,
    coopContribution: 2250,
  },
  {
    id: 'w7',
    name: 'Lakshmi Nair',
    trade: 'Caregiving',
    skills: ['Eldercare', 'Post-Operative Care', 'Childcare'],
    certifications: ['Nursing Assistant', 'First Aid Certified'],
    experienceYears: 8,
    distanceKm: 2.4,
    available: true,
    availableNow: true,
    rating: 4.9,
    jobsCompleted: 264,
    currentWorkload: 40,
    recentJobs: 18,
    verified: true,
    cooperative: 'Seva Care Cooperative',
    avatarColor: 'bg-pink-600',
    initials: 'LN',
    earningsMonth: 17600,
    welfareContribution: 880,
    coopContribution: 1760,
  },
  {
    id: 'w8',
    name: 'Deepak Singh',
    trade: 'Driving',
    skills: ['City Commute', 'Errand Driving', 'Goods Transport'],
    certifications: ['Commercial License', 'Defensive Driving Cert.'],
    experienceYears: 6,
    distanceKm: 1.5,
    available: true,
    availableNow: true,
    rating: 4.7,
    jobsCompleted: 512,
    currentWorkload: 30,
    recentJobs: 26,
    verified: true,
    cooperative: 'Safar Seva Cooperative',
    avatarColor: 'bg-indigo-600',
    initials: 'DS',
    earningsMonth: 15400,
    welfareContribution: 770,
    coopContribution: 1540,
  },
  {
    id: 'w9',
    name: 'Vikram Patel',
    trade: 'Technical Services',
    skills: ['Appliance Repair', 'AC Service', 'Device Setup'],
    certifications: ['Diploma in Electronics', 'Brand Service Partner'],
    experienceYears: 7,
    distanceKm: 3.8,
    available: true,
    availableNow: true,
    rating: 4.8,
    jobsCompleted: 234,
    currentWorkload: 44,
    recentJobs: 20,
    verified: true,
    cooperative: 'Tech Seva Cooperative',
    avatarColor: 'bg-slate-700',
    initials: 'VP',
    earningsMonth: 18900,
    welfareContribution: 945,
    coopContribution: 1890,
  },
  {
    id: 'w10',
    name: 'Gaurav Mehta',
    trade: 'Painting',
    skills: ['Interior Painting', 'Waterproofing', 'Texture Finish'],
    certifications: ['Painter ITI', 'Lead-Safe Certified'],
    experienceYears: 9,
    distanceKm: 4.6,
    available: true,
    availableNow: false,
    rating: 4.7,
    jobsCompleted: 188,
    currentWorkload: 36,
    recentJobs: 14,
    verified: true,
    cooperative: 'Kushal Seva Cooperative',
    avatarColor: 'bg-emerald-600',
    initials: 'GM',
    earningsMonth: 16700,
    welfareContribution: 835,
    coopContribution: 1670,
  },
  {
    id: 'w11',
    name: 'Ramesh Yadav',
    trade: 'Gardening',
    skills: ['Lawn Care', 'Plant Health', 'Landscaping'],
    certifications: ['Horticulture Diploma'],
    experienceYears: 5,
    distanceKm: 2.9,
    available: true,
    availableNow: true,
    rating: 4.6,
    jobsCompleted: 176,
    currentWorkload: 26,
    recentJobs: 10,
    verified: true,
    cooperative: 'Hariyali Seva Cooperative',
    avatarColor: 'bg-teal-700',
    initials: 'RY',
    earningsMonth: 12300,
    welfareContribution: 615,
    coopContribution: 1230,
  },
  {
    id: 'w12',
    name: 'Suresh Kamble',
    trade: 'Plumbing',
    skills: ['Pipe Repair', 'Bathroom Fittings', 'Motor Repair'],
    certifications: ['ITI Plumbing'],
    experienceYears: 6,
    distanceKm: 5.2,
    available: false,
    availableNow: false,
    rating: 4.5,
    jobsCompleted: 156,
    currentWorkload: 80,
    recentJobs: 40,
    verified: true,
    cooperative: 'Bharat Seva Cooperative',
    avatarColor: 'bg-cyan-700',
    initials: 'SK',
    earningsMonth: 13900,
    welfareContribution: 695,
    coopContribution: 1390,
  },
  {
    id: 'w13',
    name: 'Arjun Tiwari',
    trade: 'Electrical',
    skills: ['Wiring', 'Switch Repair', 'Fan Install'],
    certifications: ['ITI Electrical'],
    experienceYears: 3,
    distanceKm: 3.2,
    available: true,
    availableNow: true,
    rating: 4.4,
    jobsCompleted: 88,
    currentWorkload: 15,
    recentJobs: 5,
    verified: false,
    cooperative: 'Bharat Seva Cooperative',
    avatarColor: 'bg-accent-700',
    initials: 'AT',
    earningsMonth: 8200,
    welfareContribution: 410,
    coopContribution: 820,
  },
  {
    id: 'w14',
    name: 'Kamla Devi',
    trade: 'Househelp',
    skills: ['Cooking', 'Dusting', 'Utensil Cleaning', 'Daily Chores'],
    certifications: ['Hygiene Certified', 'Coop Safety Training'],
    experienceYears: 8,
    distanceKm: 1.6,
    available: true,
    availableNow: true,
    rating: 4.8,
    jobsCompleted: 296,
    currentWorkload: 50,
    recentJobs: 24,
    verified: true,
    cooperative: 'Swachh Seva Cooperative',
    avatarColor: 'bg-orange-600',
    initials: 'KD',
    earningsMonth: 12600,
    welfareContribution: 630,
    coopContribution: 1260,
  },
];

export const AREAS = [
  'Swaroop Nagar, Kanpur',
  'Civil Lines, Kanpur',
  'Kakadeo, Kanpur',
  'Kidwai Nagar, Kanpur',
  'Govind Nagar, Kanpur',
  'Arya Nagar, Kanpur',
  'Shastri Nagar, Kanpur',
  'Kalyanpur, Kanpur',
];

export const NOTIFICATIONS = [
  { id: 'n1', title: 'Worker assigned', body: 'Rajesh Kumar accepted your plumbing request.', time: '2 min ago', unread: true, type: 'success' as const },
  { id: 'n2', title: 'Booking completed', body: 'Electrical repair #SS1018 marked complete.', time: '1 hr ago', unread: true, type: 'info' as const },
  { id: 'n3', title: 'Cooperative update', body: 'Your welfare fund contribution this month: ₹920.', time: '5 hr ago', unread: false, type: 'coop' as const },
];

export const DEMAND_AREAS = [
  { area: 'Swaroop Nagar', plumbing: 82, electrical: 64, cleaning: 71, carpentry: 40, painting: 33, technical: 55, total: 345 },
  { area: 'Civil Lines', plumbing: 55, electrical: 48, cleaning: 88, carpentry: 35, painting: 60, technical: 42, total: 328 },
  { area: 'Kakadeo', plumbing: 94, electrical: 72, cleaning: 52, carpentry: 68, painting: 71, technical: 38, total: 395 },
  { area: 'Kidwai Nagar', plumbing: 41, electrical: 86, cleaning: 33, carpentry: 28, painting: 22, technical: 90, total: 300 },
  { area: 'Govind Nagar', plumbing: 48, electrical: 55, cleaning: 62, carpentry: 44, painting: 58, technical: 66, total: 333 },
];

export const WEEKLY_DEMAND = [
  { day: 'Mon', demand: 240 },
  { day: 'Tue', demand: 280 },
  { day: 'Wed', demand: 320 },
  { day: 'Thu', demand: 295 },
  { day: 'Fri', demand: 410 },
  { day: 'Sat', demand: 520 },
  { day: 'Sun', demand: 380 },
];

export const FORECAST = [
  { day: 'Mon', predicted: 250, actual: 240 },
  { day: 'Tue', predicted: 285, actual: 280 },
  { day: 'Wed', predicted: 310, actual: 320 },
  { day: 'Thu', predicted: 300, actual: 295 },
  { day: 'Fri', predicted: 420, actual: 410 },
  { day: 'Sat', predicted: 540, actual: 520 },
  { day: 'Sun', predicted: 390, actual: 380 },
  { day: 'Next Mon', predicted: 270, actual: null },
  { day: 'Next Tue', predicted: 310, actual: null },
  { day: 'Next Wed', predicted: 350, actual: null },
];

export const REVENUE_SPLIT = [
  { label: 'Worker Earnings', value: 82, color: '#12b76a' },
  { label: 'Cooperative Operations', value: 10, color: '#399bfb' },
  { label: 'Worker Welfare Fund', value: 8, color: '#14a8b3' },
];

export const COOP_SUMMARY = {
  totalEarnings: 18450,
  coopContribution: 1845,
  welfareFund: 920,
  avgWorkerIncome: 16800,
  jobsCompleted: 342,
  activeWorkers: 12,
  totalCoopRevenue: 248600,
  totalWelfareFunds: 19880,
};

export const DAMAGE_INSURANCE_LIMIT = 5000;
export const WARRANTY_DAYS = 3;

export const TECH_ARCHITECTURE = [
  { icon: 'Cloud', title: 'Cloud Computing', desc: 'Supabase-powered backend with edge functions, PostgreSQL database and object storage for worker profiles, bookings and welfare records.', color: 'text-secondary-600 bg-secondary-50' },
  { icon: 'Sparkles', title: 'Artificial Intelligence', desc: 'NLP service interpretation, demand forecasting model and fair-allocation engine balancing skill, distance, workload and recent jobs.', color: 'text-primary-600 bg-primary-50' },
  { icon: 'Map', title: 'Geo-Spatial Technology', desc: 'Simulated geo-location matching, community demand heatmap and area-based workforce deployment visualisation.', color: 'text-teal-600 bg-teal-50' },
  { icon: 'Wallet', title: 'Digital Payment Systems', desc: 'Transparent charge breakdown with worker earnings, cooperative operations, welfare contribution and damage insurance before payment.', color: 'text-accent-600 bg-accent-50' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {},
  hi: {
    'SahkaarServe': 'सहकारसेवा',
    'Cooperative Service Platform': 'सहकारी सेवा प्लेटफ़ॉर्म',
    'Customer Portal': 'ग्राहक पोर्टल',
    'Cooperative Worker Portal': 'सहकारी कर्मचारी पोर्टल',
    'What help do you need?': 'आपको क्या मदद चाहिए?',
    'Ask AI': 'एआई से पूछें',
    'Home': 'होम',
    'My Bookings': 'मेरी बुकिंग',
    'Emergency Service': 'आपातकालीन सेवा',
    'AI Service Request': 'एआई सेवा अनुरोध',
    'Dashboard': 'डैशबोर्ड',
    'Jobs': 'कार्य',
    'Earnings': 'कमाई',
    'Cooperative Economics': 'सहकारी अर्थव्यवस्था',
    'My Benefits': 'मेरे लाभ',
    'Skills & Certificates': 'कौशल और प्रमाणपत्र',
    'Availability': 'उपलब्धता',
    'Overview': 'अवलोकन',
    'Workers': 'कर्मचारी',
    'Bookings': 'बुकिंग',
    'Demand Heatmap': 'मांग हीटमैप',
    'Demand Forecasting': 'मांग पूर्वानुमान',
    'AI Workforce Allocation': 'एआई कार्यबल आवंटन',
    'Service categories': 'सेवा श्रेणियाँ',
    'Active booking': 'सक्रिय बुकिंग',
    'Total bookings': 'कुल बुकिंग',
    'Verified workers': 'सत्यापित कर्मचारी',
    'Browse services': 'सेवाएँ ब्राउज़ करें',
    'Rate your experience': 'अपना अनुभव रेट करें',
    'Pay Now': 'अभी भुगतान करें',
    'Confirm booking': 'बुकिंग की पुष्टि करें',
    'Exit demo': 'डेमो से बाहर',
    'Welfare': 'कल्याण',
    'Technology': 'प्रौद्योगिकी',
    'Good afternoon, Priya': 'नमस्ते, प्रिया',
    'Browse our service categories or let our AI understand your problem.': 'हमारी सेवा श्रेणियाँ ब्राउज़ करें या एआई को अपनी समस्या बताएं।',
    'Popular services': 'लोकप्रिय सेवाएँ',
    'Notifications': 'सूचनाएँ',
    'No active booking': 'कोई सक्रिय बुकिंग नहीं',
    'Pick a category above to start a new service request.': 'नई सेवा अनुरोध के लिए ऊपर एक श्रेणी चुनें।',
    'Recent bookings': 'हाल की बुकिंग',
    'View all': 'सभी देखें',
    'Burst pipe? Spark? Get urgent help now.': 'पाइप फटा? चिंगारी? अभी तत्काल सहायता पाएं।',
    'Not sure what service you need?': 'निश्चित नहीं कि कौन सी सेवा चाहिए?',
    'Describe your problem in your own words and let SahkaarServe AI find the right service and best worker for you.': 'अपनी समस्या शब्दों में बताएं और सहकारसेवा एआई को सही सेवा और सर्वश्रेष्ठ कर्मचारी खोजने दें।',
    'Ask SahkaarServe AI': 'सहकारसेवा एआई से पूछें',
    'Avg response': 'औसत प्रतिक्रिया',
    'In your area': 'आपके क्षेत्र में',
    'Nearby': 'पास में',
    'No active job': 'कोई सक्रिय कार्य नहीं',
    'Available now': 'अभी उपलब्ध',
    'Available': 'उपलब्ध',
    'Busy': 'व्यस्त',
    'Verified': 'सत्यापित',
    'onwards': 'से शुरू',
    'Book / Select': 'बुक करें / चुनें',
    'Available Professionals': 'उपलब्ध पेशेवर',
    'verified cooperative workers near you': 'आपके पास सत्यापित सहकारी कर्मचारी',
    'Sort by:': 'क्रमबद्ध करें:',
    'Top Rated': 'शीर्ष रेटेड',
    'Nearest': 'निकटतम',
    'Most Experienced': 'सबसे अनुभवी',
    'Lowest Price': 'सबसे कम मूल्य',
    'years': 'वर्ष',
    'yrs': 'वर्ष',
    'jobs': 'कार्य',
    'km': 'किमी',
    'away': 'दूर',
    'Back to services': 'सेवाओं पर वापस',
    'Back to home': 'होम पर वापस',
    'Back': 'वापस',
    'Describe your problem in plain language. Our AI will understand the service, sub-service and priority for you.': 'अपनी समस्या सरल भाषा में बताएं। हमारा एआई सेवा, उप-सेवा और प्राथमिकता समझ लेगा।',
    'Describe your request': 'अपना अनुरोध बताएं',
    'Interpret with AI': 'एआई से व्याख्या करें',
    'Press Enter to submit': 'जमा करने के लिए Enter दबाएं',
    'AI Understanding': 'एआई समझ',
    'Service': 'सेवा',
    'Sub-service': 'उप-सेवा',
    'Priority': 'प्राथमिकता',
    'Location': 'स्थान',
    'Available Verified Workers': 'उपलब्ध सत्यापित कर्मचारी',
    'nearby': 'पास में',
    'Find Best Worker': 'सर्वश्रेष्ठ कर्मचारी खोजें',
    'Issue': 'समस्या',
    'Track all your service requests and their live status.': 'अपने सभी सेवा अनुरोध और उनकी लाइव स्थिति देखें।',
    'No bookings yet': 'अभी कोई बुकिंग नहीं',
    'Pick a category to start your first booking.': 'अपनी पहली बुकिंग के लिए एक श्रेणी चुनें।',
    'Report an urgent problem. We dispatch the nearest available verified worker immediately.': 'तत्काल समस्या रिपोर्ट करें। हम तुरंत निकटतम उपलब्ध सत्यापित कर्मचारी भेजते हैं।',
    'What is the emergency?': 'आपातकाल क्या है?',
    'Dispatch Now': 'अभी भेजें',
    'Analyzing emergency…': 'आपातकाल का विश्लेषण कर रहे हैं…',
    'Emergency Priority: HIGH': 'आपातकालीन प्राथमिकता: उच्च',
    'Emergency': 'आपातकालीन',
    'Select Date': 'तारीख चुनें',
    'Select date': 'तारीख चुनें',
    'Select time slot': 'समय स्लॉट चुनें',
    'Dispatch immediately (Now)': 'तुरंत भेजें (अभी)',
    'Now': 'अभी',
    'Morning': 'सुबह',
    'Afternoon': 'दोपहर',
    'Evening': 'शाम',
    'Problem description': 'समस्या का विवरण',
    'Booking summary': 'बुकिंग सारांश',
    'Worker': 'कर्मचारी',
    'Date': 'तारीख',
    'Time': 'समय',
    'Estimated cost': 'अनुमानित लागत',
    'Final cost confirmed after service completion.': 'सेवा पूर्ण होने के बाद अंतिम लागत की पुष्टि।',
    'Emergency dispatch': 'आपातकालीन भेजना',
    'The worker will be alerted immediately and dispatched as a priority job.': 'कर्मचारी को तुरंत सूचित किया जाएगा और प्राथमिकता कार्य के रूप में भेजा जाएगा।',
    'Booking Confirmed!': 'बुकिंग की पुष्टि हुई!',
    'Your request has been sent to the worker': 'आपका अनुरोध कर्मचारी को भेजा गया है',
    'Emergency worker dispatched': 'आपातकालीन कर्मचारी भेजा गया',
    'Booking timeline': 'बुकिंग समयरेखा',
    'View my bookings': 'मेरी बुकिंग देखें',
    'You are about to book': 'आप बुक करने जा रहे हैं',
    'for': 'के लिए',
    'Cooperative Operations Center': 'सहकारी संचालन केंद्र',
    'Real-time view of workers, demand and fair allocation across all service areas.': 'सभी सेवा क्षेत्रों में कर्मचारियों, मांग और निष्पक्ष आवंटन का वास्तविक समय दृश्य।',
    'Active workers': 'सक्रिय कर्मचारी',
    'Active bookings': 'सक्रिय बुकिंग',
    'Avg rating': 'औसत रेटिंग',
    'Coop revenue': 'सहकारी आय',
    'This month': 'इस महीने',
    'Weekly demand trend': 'साप्ताहिक मांग रुझान',
    'Forecast': 'पूर्वानुमान',
    'Fair Allocation status': 'निष्पक्ष आवंटन स्थिति',
    'Job distribution across active workers (last 7 days)': 'सक्रिय कर्मचारियों में कार्य वितरण (पिछले 7 दिन)',
    'Community Demand Heatmap': 'सामुदायिक मांग हीटमैप',
    'Optimize worker deployment': 'कर्मचारी तैनाती अनुकूलित करें',
    'See demand by area and service': 'क्षेत्र और सेवा अनुसार मांग देखें',
    'All Bookings': 'सभी बुकिंग',
    'Monitor and manage service requests across the cooperative.': 'सहकारी के सभी सेवा अनुरोध देखें और प्रबंधित करें।',
    'All': 'सभी',
    'Manage your cooperative verified workforce.': 'अपने सहकारी के सत्यापित कर्मचारी प्रबंधित करें।',
    'Search by name or trade…': 'नाम या व्यवसाय से खोजें…',
    'Workload': 'कार्यभार',
    'Recent jobs': 'हाल के कार्य',
    'Cooperative-wide revenue, worker earnings and welfare fund overview.': 'सहकारी-व्यापी आय, कर्मचारी कमाई और कल्याण कोष का अवलोकन।',
    'Total revenue': 'कुल आय',
    'Worker payouts': 'कर्मचारी भुगतान',
    'to workers': 'कर्मचारियों को',
    'Welfare fund': 'कल्याण कोष',
    'reserved': 'आरक्षित',
    'Avg income': 'औसत आय',
    'Per worker': 'प्रति कर्मचारी',
    'Revenue distribution': 'आय वितरण',
    'Cooperative principles': 'सहकारी सिद्धांत',
    'Top earning workers this month': 'इस महीने शीर्ष कमाई करने वाले कर्मचारी',
    'AI Demand Forecasting': 'एआई मांग पूर्वानुमान',
    'Predictive model trained on cooperative service history to optimize worker deployment.': 'कर्मचारी तैनाती अनुकूलित करने के लिए सहकारी सेवा इतिहास पर प्रशिक्षित भविष्यवाणी मॉडल।',
    'Predicted vs actual demand': 'पूर्वानुमानित बनाम वास्तविक मांग',
    'AI Model': 'एआई मॉडल',
    'Model accuracy': 'मॉडल सटीकता',
    'Next peak': 'अगला शिखर',
    'Suggested workers': 'सुझाए गए कर्मचारी',
    'AI insights recommendations': 'एआई अंतर्दृष्टि और सुझाव',
    'AI insights & recommendations': 'एआई अंतर्दृष्टि और सुझाव',
    'Fair Allocation Engine': 'निष्पक्ष आवंटन इंजन',
    'Deployments balance demand coverage with fair job distribution.': 'तैनाती मांग कवरेज को निष्पक्ष कार्य वितरण के साथ संतुलित करती है।',
    'Allocation score': 'आवंटन स्कोर',
    'fit': 'मेल',
    'Workload distribution (all workers)': 'कार्यभार वितरण (सभी कर्मचारी)',
    'recent': 'हाल का',
    'load': 'भार',
    'Welcome back,': 'वापसी पर स्वागत है,',
    'Today jobs': 'आज के कार्य',
    "Today's jobs": 'आज के कार्य',
    'Upcoming jobs': 'आगामी कार्य',
    'This month earnings': 'इस महीने की कमाई',
    'Rating': 'रेटिंग',
    'pending': 'लंबित',
    'No jobs today': 'आज कोई कार्य नहीं',
    'New jobs will appear here as customers request services.': 'जैसे ही ग्राहक सेवा अनुरोध करेंगे, नए कार्य यहां दिखेंगे।',
    'No upcoming jobs': 'कोई आगामी कार्य नहीं',
    'Recently completed': 'हाल में पूर्ण',
    'Current workload': 'वर्तमान कार्यभार',
    'Healthy': 'स्वस्थ',
    'High': 'उच्च',
    'Verification status': 'सत्यापन स्थिति',
    'Verification Pending': 'सत्यापन लंबित',
    'Verification Pending — awaiting cooperative admin review.': 'सत्यापन लंबित — सहकारी व्यवस्थापक समीक्षा की प्रतीक्षा में।',
    'Identity / contact check': 'पहचान / संपर्क जांच',
    'Skill assessment (practical)': 'कौशल मूल्यांकन (व्यावहारिक)',
    'Cooperative review': 'सहकारी समीक्षा',
    'References / previous work': 'संदर्भ / पिछला कार्य',
    'Cooperative Verified': 'सहकारी सत्यापित',
    'See how your earnings are shared fairly.': 'देखें कि आपकी कमाई कैसे निष्पक्ष रूप से साझा की जाती है।',
    'Your cooperative-first income breakdown.': 'आपकी सहकारी-प्रथम आय विभाजन।',
    'Jobs completed': 'पूर्ण कार्य',
    'Avg / job': 'औसत / कार्य',
    'Monthly earnings': 'मासिक कमाई',
    'Recent payouts': 'हाल के भुगतान',
    'See how your service income is transparently shared.': 'देखें कि आपकी सेवा आय पारदर्शी रूप से कैसे साझा की जाती है।',
    'Example Service Amount': 'उदाहरण सेवा राशि',
    'Total Service Amount': 'कुल सेवा राशि',
    'Your Earnings': 'आपकी कमाई',
    'Cooperative Contribution': 'सहकारी योगदान',
    'operations platform': 'संचालन और प्लेटफ़ॉर्म',
    'Worker Welfare Fund': 'कर्मचारी कल्याण कोष',
    'health, insurance, tools': 'स्वास्थ्य, बीमा, उपकरण',
    'You Receive': 'आपको प्राप्त',
    'Transparent income sharing': 'पारदर्शी आय साझाकरण',
    'Your service income is transparently divided between your earnings, cooperative contribution and worker welfare support.': 'आपकी सेवा आय आपकी कमाई, सहकारी योगदान और कर्मचारी कल्याण सहायता के बीच पारदर्शी रूप से विभाजित होती है।',
    'My Cooperative Benefits': 'मेरे सहकारी लाभ',
    'As a verified cooperative member, you receive benefits beyond your earnings.': 'सत्यापित सहकारी सदस्य के रूप में, आपको कमाई से परे लाभ मिलते हैं।',
    'Earnings this month': 'इस महीने की कमाई',
    'Welfare contribution': 'कल्याण योगदान',
    'Auto-saved': 'स्वतः-सहेजा गया',
    'Coop contribution': 'सहकारी योगदान',
    'share': 'हिस्सा',
    'Total benefits': 'कुल लाभ',
    'This year': 'इस वर्ष',
    'Health Insurance': 'स्वास्थ्य बीमा',
    'Family health coverage funded by the welfare pool.': 'कल्याण कोष से वित्तपोषित परिवार स्वास्थ्य कवरेज।',
    'Active': 'सक्रिय',
    'Accident Cover': 'दुर्घटना कवर',
    'On-the-job accident protection while working.': 'काम करते समय नौकरी पर दुर्घटना सुरक्षा।',
    'cover': 'कवर',
    'Skill Upgradation': 'कौशल उन्नयन',
    'Free certification courses through the cooperative.': 'सहकारी के माध्यम से निःशुल्क प्रमाणन पाठ्यक्रम।',
    'courses': 'पाठ्यक्रम',
    'Savings Fund': 'बचत कोष',
    'Mandatory welfare contribution grows your savings.': 'अनिवार्य कल्याण योगदान आपकी बचत बढ़ाता है।',
    'Tool Subsidy': 'उपकरण सब्सिडी',
    '50% subsidy on professional tools and equipment.': 'पेशेवर उपकरणों और उपकरणों पर 50% सब्सिडी।',
    'Up to': 'अधिकतम',
    'Cooperative Voting': 'सहकारी मतदान',
    'Vote on cooperative decisions and policies.': 'सहकारी निर्णयों और नीतियों पर मतदान करें।',
    '1 share': '1 हिस्सा',
    'Life Insurance': 'जीवन बीमा',
    'Life cover for cooperative members funded by welfare pool.': 'कल्याण कोष से वित्तपोषित सहकारी सदस्यों के लिए जीवन कवर।',
    'Skills': 'कौशल',
    'Your verified skills and professional certifications.': 'आपके सत्यापित कौशल और पेशेवर प्रमाणपत्र।',
    'Certifications': 'प्रमाणपत्र',
    'Issued by': 'जारीकर्ता',
    'Control when you receive job assignments. The Fair Allocation Engine respects your preferences.': 'नियंत्रित करें कब आप कार्य असाइनमेंट प्राप्त करें। निष्पक्ष आवंटन इंजन आपकी प्राथमिकताओं का सम्मान करता है।',
    'Availability status': 'उपलब्धता स्थिति',
    'You are receiving job requests': 'आप कार्य अनुरोध प्राप्त कर रहे हैं',
    'You are currently unavailable': 'आप वर्तमान में अनुपलब्ध हैं',
    'Available for emergency dispatch': 'आपातकालीन भेजने के लिए उपलब्ध',
    'Receive urgent high-priority jobs immediately': 'तत्काल उच्च-प्राथमिकता कार्य तुरंत प्राप्त करें',
    "Today's time slots": 'आज के समय स्लॉट',
    "Select when you're free to accept jobs": 'चुनें कब आप कार्य स्वीकार करने के लिए स्वतंत्र हैं',
    'Fair Allocation impact': 'निष्पक्ष आवंटन प्रभाव',
    'Your current workload': 'आपका वर्तमान कार्यभार',
    'Recent jobs (7 days)': 'हाल के कार्य (7 दिन)',
    'Service Started': 'सेवा शुरू',
    'Service Completed': 'सेवा पूर्ण',
    'Completed': 'पूर्ण',
    'Rejected': 'अस्वीकृत',
    'Accepted': 'स्वीकृत',
    'On the Way': 'रास्ते में',
    'Househelp': 'घरेलू सहायता',
    'Cooking, dusting, daily chores': 'खाना बनाना, सफ़ाई, रोज़ के काम',
    'Requested': 'अनुरोधित',
    'Rated': 'रेटेड',
    'Paid': 'भुगतान किया',
    'Accept': 'स्वीकारें',
    'Reject': 'अस्वीकारें',
    'Advance status': 'अगला चरण',
    'Advance to next status': 'अगले चरण पर जाएं',
    'Service completed. Rate your experience.': 'सेवा पूर्ण। अपना अनुभव रेट करें।',
    'No bookings in this filter': 'इस फ़िल्टर में कोई बुकिंग नहीं',
    'Total Workers': 'कुल कर्मचारी',
    'Active Workers': 'सक्रिय कर्मचारी',
    'Verified Workers': 'सत्यापित कर्मचारी',
    'Pending Verification': 'सत्यापन लंबित',
    'Cooperative Revenue': 'सहकारी आय',
    'Total Welfare Funds': 'कुल कल्याण कोष',
    'AI Recommendation': 'एआई सुझाव',
    'Payment & Price Breakdown': 'भुगतान और मूल्य विभाजन',
    'Worker Earnings': 'कर्मचारी कमाई',
    'Cooperative Operations': 'सहकारी संचालन',
    'Total Amount': 'कुल राशि',
    'Payment Method': 'भुगतान विधि',
    'UPI': 'यूपीआई',
    'Card': 'कार्ड',
    'Net Banking': 'नेट बैंकिंग',
    'Pay & Confirm': 'भुगतान करें और पुष्टि करें',
    'Invoice': 'चालान',
    'Damage Insurance Premium': 'क्षति बीमा प्रीमियम',
    'Welfare Fund Contribution': 'कल्याण कोष योगदान',
    'Rating Feedback': 'रेटिंग और प्रतिक्रिया',
    'Complaint': 'शिकायत',
    '3-Day Warranty': '3-दिन वारंटी',
    'Damage Insurance': 'क्षति बीमा',
    'Submit Rating': 'रेटिंग जमा करें',
    'File Complaint': 'शिकायत दर्ज करें',
    'Claim Warranty': 'वारंटी दावा करें',
    'Claim Insurance': 'बीमा दावा करें',
    'If the same issue occurs within 3 days, claim free re-service.': 'यदि 3 दिनों के भीतर वही समस्या आती है, तो निःशुल्क पुनः-सेवा का दावा करें।',
    'If worker accidentally damages your property, claim compensation up to ₹5,000.': 'यदि कर्मचारी गलती से आपकी संपत्ति को नुकसान पहुंचाता है, तो ₹5,000 तक का मुआवजा पाएं।',
    'Select skills': 'कौशल चुनें',
    'Choose one or more skills': 'एक या अधिक कौशल चुनें',
    'Customer': 'ग्राहक',
    'Cooperative Worker': 'सहकारी कर्मचारी',
    'Login': 'लॉगिन',
    'Sign Up': 'साइन अप',
    'Mobile or Email': 'मोबाइल या ईमेल',
    'Password / OTP': 'पासवर्ड / ओटीपी',
    'Full Name': 'पूरा नाम',
    'Mobile Number': 'मोबाइल नंबर',
    'Email (optional)': 'ईमेल (वैकल्पिक)',
    'Service Details': 'सेवा विवरण',
    'Service Category': 'सेवा श्रेणी',
    'Experience (years)': 'अनुभव (वर्ष)',
    'Service Area': 'सेवा क्षेत्र',
    'Demo mode: enter any mobile/email and password to log in.': 'डेमो मोड: लॉगिन के लिए कोई भी मोबाइल/ईमेल और पासवर्ड दर्ज करें।',
    'Logging in…': 'लॉगिन हो रहा है…',
    'Creating account…': 'खाता बन रहा है…',
    'Demo credentials are pre-filled. Just click Login to enter the administrator dashboard.': 'डेमो क्रेडेंशियल पहले से भरे हैं। व्यवस्थापक डैशबोर्ड में प्रवेश के लिए बस लॉगिन क्लिक करें।',
    'Authenticating…': 'प्रमाणीकरण हो रहा है…',
    'New workers start with Verification Pending status.': 'नए कर्मचारी सत्यापन लंबित स्थिति के साथ शुरू होते हैं।',
    'The cooperative admin will review your identity, skills and references before approval.': 'सहकारी व्यवस्थापक आपकी पहचान, कौशल और संदर्भ समीक्षा करेंगे।',
    'Choose a demo role to continue': 'जारी रखने के लिए एक डेमो भूमिका चुनें',
    'Find and book service professionals.': 'सेवा पेशेवर खोजें और बुक करें।',
    'Manage jobs, availability and earnings.': 'कार्य, उपलब्धता और कमाई प्रबंधित करें।',
    'Continue as': 'जारी रखें',
    'Cooperative Administrator Login': 'सहकारी व्यवस्थापक लॉगिन',
    'Restricted access · Staff only': 'प्रतिबंधित पहुंच · केवल स्टाफ',
    'Email': 'ईमेल',
    'Password': 'पासवर्ड',
    'Login as Administrator': 'व्यवस्थापक के रूप में लॉगिन करें',
    'Language': 'भाषा',
    'Best Workers for Your Request': 'आपके अनुरोध के लिए सर्वश्रेष्ठ कर्मचारी',
    'Recommended based on skill, availability, distance, rating and workload.': 'कौशल, उपलब्धता, दूरी, रेटिंग और कार्यभार के आधार पर अनुशंसित।',
    'AI Recommended — Best Match': 'एआई अनुशंसित — सर्वश्रेष्ठ मेल',
    'Match': 'मेल',
    'Other matched workers': 'अन्य मेल खाने वाले कर्मचारी',
    'Fair Match': 'निष्पक्ष मेल',
    'Current Workload': 'वर्तमान कार्यभार',
    'Recent Jobs': 'हाल के कार्य',
    'this week': 'इस सप्ताह',
    'verified': 'सत्यापित',
    'Why this match?': 'यह मेल क्यों?',
    'Skill relevance': 'कौशल प्रासंगिकता',
    'Distance': 'दूरी',
    'Experience': 'अनुभव',
    'Dispatch Worker': 'कर्मचारी भेजें',
    'Select': 'चुनें',
    'View Profile': 'प्रोफ़ाइल देखें',
    'Hide profile': 'प्रोफ़ाइल छुपाएं',
    'About': 'परिचय',
    'Jobs Completed': 'पूर्ण कार्य',
    'Avg Rating': 'औसत रेटिंग',
    'Demand across areas': 'क्षेत्रों में मांग',
    'Low': 'कम',
    'Saturday peak predicted': 'शनिवार शिखर की भविष्यवाणी',
    'Electrical surge': 'विद्युत वृद्धि',
    'Cleaning demand rising': 'सफाई मांग बढ़ रही है',
  },
  pa: {
    'SahkaarServe': 'ਸਹਿਕਾਰਸੇਵਾ',
    'Cooperative Service Platform': 'ਸਹਿਕਾਰੀ ਸੇਵਾ ਪਲੇਟਫਾਰਮ',
    'Customer Portal': 'ਗਾਹਕ ਪੋਰਟਲ',
    'Cooperative Worker Portal': 'ਸਹਿਕਾਰੀ ਕਰਮਚਾਰੀ ਪੋਰਟਲ',
    'What help do you need?': 'ਤੁਹਾਨੂੰ ਕਿਹੜੀ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?',
    'Ask AI': 'ਏਆਈ ਨੂੰ ਪੁੱਛੋ',
    'Home': 'ਹੋਮ',
    'My Bookings': 'ਮੇਰੀ ਬੁਕਿੰਗ',
    'Emergency Service': 'ਐਮਰਜੈਂਸੀ ਸੇਵਾ',
    'AI Service Request': 'ਏਆਈ ਸੇਵਾ ਬੇਨਤੀ',
    'Dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'Jobs': 'ਕੰਮ',
    'Earnings': 'ਕਮਾਈ',
    'Cooperative Economics': 'ਸਹਿਕਾਰੀ ਅਰਥਚਾਰਾ',
    'My Benefits': 'ਮੇਰੇ ਲਾਭ',
    'Skills & Certificates': 'ਹੁਨਰ ਅਤੇ ਸਰਟੀਫਿਕੇਟ',
    'Availability': 'ਉਪਲਬਧਤਾ',
    'Overview': 'ਸੰਖੇਪ',
    'Workers': 'ਕਰਮਚਾਰੀ',
    'Bookings': 'ਬੁਕਿੰਗ',
    'Demand Heatmap': 'ਮੰਗ ਹੀਟਮੈਪ',
    'Demand Forecasting': 'ਮੰਗ ਪੂਰਵ-ਅਨੁਮਾਨ',
    'AI Workforce Allocation': 'ਏਆਈ ਕਾਰਜਬਲ ਵੰਪ',
    'Service categories': 'ਸੇਵਾ ਸ਼੍ਰੇਣੀਆਂ',
    'Active booking': 'ਸਰਗਰਮ ਬੁਕਿੰਗ',
    'Total bookings': 'ਕੁਲ ਬੁਕਿੰਗ',
    'Verified workers': 'ਪ੍ਰਮਾਣਿਤ ਕਰਮਚਾਰੀ',
    'Browse services': 'ਸੇਵਾਵਾਂ ਬ੍ਰਾਊਜ਼ ਕਰੋ',
    'Rate your experience': 'ਆਪਣਾ ਤਜਰਬਾ ਰੇਟ ਕਰੋ',
    'Pay Now': 'ਹੁਣ ਭੁਗਤਾਨ ਕਰੋ',
    'Confirm booking': 'ਬੁਕਿੰਗ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    'Exit demo': 'ਡੈਮੋ ਤੋਂ ਬਾਹਰ',
    'Welfare': 'ਭਲਾਈ',
    'Technology': 'ਤਕਨਾਲੋਜੀ',
    'Good afternoon, Priya': 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਪ੍ਰਿਆ',
    'Popular services': 'ਪ੍ਰਸਿੱਧ ਸੇਵਾਵਾਂ',
    'Notifications': 'ਸੂਚਨਾਵਾਂ',
    'No active booking': 'ਕੋਈ ਸਰਗਰਮ ਬੁਕਿੰਗ ਨਹੀਂ',
    'Recent bookings': 'ਹਾਲੀਆ ਬੁਕਿੰਗਾਂ',
    'View all': 'ਸਭ ਵੇਖੋ',
    'Not sure what service you need?': 'ਯਕੀਨੀ ਨਹੀਂ ਕਿ ਤੁਹਾਨੂੰ ਕਿਹੜੀ ਸੇਵਾ ਚਾਹੀਦੀ ਹੈ?',
    'Ask SahkaarServe AI': 'ਸਹਿਕਾਰਸੇਵਾ ਏਆਈ ਨੂੰ ਪੁੱਛੋ',
    'Avg response': 'ਔਸਤ ਜਵਾਬ',
    'In your area': 'ਤੁਹਾਡੇ ਖੇਤਰ ਵਿੱਚ',
    'Nearby': 'ਨੇੜੇ',
    'No active job': 'ਕੋਈ ਸਰਗਰਮ ਕੰਮ ਨਹੀਂ',
    'Available now': 'ਹੁਣ ਉਪਲਬਧ',
    'Available': 'ਉਪਲਬਧ',
    'Busy': 'ਰੁੱਝਿਆ',
    'Verified': 'ਪ੍ਰਮਾਣਿਤ',
    'onwards': 'ਤੋਂ ਸ਼ੁਰੂ',
    'Book / Select': 'ਬੁੱਕ ਕਰੋ / ਚੁਣੋ',
    'Available Professionals': 'ਉਪਲਬਧ ਪੇਸ਼ੇਵਰ',
    'Sort by:': 'ਕ੍ਰਮਬੱਧ ਕਰੋ:',
    'Top Rated': 'ਸਿਖਰਲੀ ਰੇਟਿੰਗ',
    'Nearest': 'ਸਭ ਤੋਂ ਨੇੜੇ',
    'Most Experienced': 'ਸਭ ਤੋਂ ਤਜਰਬੇਕਾਰ',
    'Lowest Price': 'ਸਭ ਤੋਂ ਘੱਟ ਕੀਮਤ',
    'years': 'ਸਾਲ',
    'yrs': 'ਸਾਲ',
    'jobs': 'ਕੰਮ',
    'km': 'ਕਿਮੀ',
    'away': 'ਦੂਰ',
    'Back to services': 'ਸੇਵਾਵਾਂ ਤੇ ਵਾਪਸ',
    'Back to home': 'ਹੋਮ ਤੇ ਵਾਪਸ',
    'Back': 'ਵਾਪਸ',
    'Describe your request': 'ਆਪਣੀ ਬੇਨਤੀ ਦੱਸੋ',
    'Interpret with AI': 'ਏਆਈ ਨਾਲ ਸਮਝੋ',
    'AI Understanding': 'ਏਆਈ ਸਮਝ',
    'Service': 'ਸੇਵਾ',
    'Sub-service': 'ਉਪ-ਸੇਵਾ',
    'Priority': 'ਤਰਜੀਹ',
    'Location': 'ਟਿਕਾਣਾ',
    'Available Verified Workers': 'ਉਪਲਬਧ ਪ੍ਰਮਾਣਿਤ ਕਰਮਚਾਰੀ',
    'nearby': 'ਨੇੜੇ',
    'Find Best Worker': 'ਸਭ ਤੋਂ ਵਧੀਆ ਕਰਮਚਾਰੀ ਲੱਭੋ',
    'Issue': 'ਸਮੱਸਿਆ',
    'Track all your service requests and their live status.': 'ਆਪਣੀਆਂ ਸਾਰੀਆਂ ਸੇਵਾ ਬੇਨਤੀਆਂ ਅਤੇ ਉਹਨਾਂ ਦੀ ਸਥਿਤੀ ਵੇਖੋ।',
    'No bookings yet': 'ਹਾਲੇ ਕੋਈ ਬੁਕਿੰਗ ਨਹੀਂ',
    'What is the emergency?': 'ਐਮਰਜੈਂਸੀ ਕੀ ਹੈ?',
    'Dispatch Now': 'ਹੁਣੇ ਭੇਜੋ',
    'Emergency Priority: HIGH': 'ਐਮਰਜੈਂਸੀ ਤਰਜੀਹ: ਉੱਚ',
    'Emergency': 'ਐਮਰਜੈਂਸੀ',
    'Select Date': 'ਤਾਰੀਖ ਚੁਣੋ',
    'Select date': 'ਤਾਰੀਖ ਚੁਣੋ',
    'Select time slot': 'ਸਮਾਂ ਚੁਣੋ',
    'Dispatch immediately (Now)': 'ਤੁਰੰਤ ਭੇਜੋ (ਹੁਣ)',
    'Now': 'ਹੁਣ',
    'Morning': 'ਸਵੇਰ',
    'Afternoon': 'ਦੁਪਹਿਰ',
    'Evening': 'ਸ਼ਾਮ',
    'Worker': 'ਕਰਮਚਾਰੀ',
    'Date': 'ਤਾਰੀਖ',
    'Time': 'ਸਮਾਂ',
    'Estimated cost': 'ਅਨੁਮਾਨਿਤ ਲਾਗਤ',
    'Booking Confirmed!': 'ਬੁਕਿੰਗ ਦੀ ਪੁਸ਼ਟੀ ਹੋਈ!',
    'Booking timeline': 'ਬੁਕਿੰਗ ਸਮਾਂਰੇਖਾ',
    'View my bookings': 'ਮੇਰੀ ਬੁਕਿੰਗ ਵੇਖੋ',
    'Cooperative Operations Center': 'ਸਹਿਕਾਰੀ ਸੰਚਾਲਨ ਕੇਂਦਰ',
    'Active workers': 'ਸਰਗਰਮ ਕਰਮਚਾਰੀ',
    'Active bookings': 'ਸਰਗਰਮ ਬੁਕਿੰਗਾਂ',
    'Avg rating': 'ਔਸਤ ਰੇਟਿੰਗ',
    'Coop revenue': 'ਸਹਿਕਾਰੀ ਆਮਦਨ',
    'This month': 'ਇਸ ਮਹੀਨੇ',
    'Weekly demand trend': 'ਹਫਤਾਵਾਰੀ ਮੰਗ ਰੁਝਾਨ',
    'Forecast': 'ਪੂਰਵ ਅਨੁਮਾਨ',
    'Community Demand Heatmap': 'ਭਾਈਚਾਰਕ ਮੰਗ ਹੀਟਮੈਪ',
    'All Bookings': 'ਸਾਰੀਆਂ ਬੁਕਿੰਗਾਂ',
    'All': 'ਸਭ',
    'Manage your cooperative verified workforce.': 'ਆਪਣੀ ਸਹਿਕਾਰੀ ਪ੍ਰਮਾਣਿਤ ਕਾਰਜਸ਼ਕਤੀ ਪ੍ਰਬੰਧਿਤ ਕਰੋ।',
    'Search by name or trade…': 'ਨਾਮ ਜਾਂ ਕਿੱਤੇ ਦੁਆਰਾ ਖੋਜੋ…',
    'Workload': 'ਕੰਮ ਦਾ ਬੋਝ',
    'Recent jobs': 'ਹਾਲੀਆ ਕੰਮ',
    'Total revenue': 'ਕੁੱਲ ਆਮਦਨ',
    'Worker payouts': 'ਕਰਮਚਾਰੀ ਭੁਗਤਾਨ',
    'Welfare fund': 'ਭਲਾਈ ਫੰਡ',
    'Avg income': 'ਔਸਤ ਆਮਦਨ',
    'Per worker': 'ਪ੍ਰਤੀ ਕਰਮਚਾਰੀ',
    'Revenue distribution': 'ਆਮਦਨ ਵੰਡ',
    'AI Demand Forecasting': 'ਏਆਈ ਮੰਗ ਪੂਰਵ ਅਨੁਮਾਨ',
    'AI Model': 'ਏਆਈ ਮਾਡਲ',
    'Model accuracy': 'ਮਾਡਲ ਸ਼ੁੱਧਤਾ',
    'Next peak': 'ਅਗਲੀ ਸਿਖਰ',
    'Suggested workers': 'ਸੁਝਾਏ ਕਰਮਚਾਰੀ',
    'Fair Allocation Engine': 'ਨਿਰਪੱਖ ਵੰਡ ਇੰਜਣ',
    'Allocation score': 'ਵੰਡ ਸਕੋਰ',
    'Welcome back,': 'ਵਾਪਸੀ ਤੇ ਸਵਾਗਤ ਹੈ,',
    "Today's jobs": 'ਅੱਜ ਦੇ ਕੰਮ',
    'Upcoming jobs': 'ਆਉਣ ਵਾਲੇ ਕੰਮ',
    'This month earnings': 'ਇਸ ਮਹੀਨੇ ਦੀ ਕਮਾਈ',
    'Rating': 'ਰੇਟਿੰਗ',
    'No jobs today': 'ਅੱਜ ਕੋਈ ਕੰਮ ਨਹੀਂ',
    'No upcoming jobs': 'ਕੋਈ ਆਉਣ ਵਾਲਾ ਕੰਮ ਨਹੀਂ',
    'Recently completed': 'ਹਾਲ ਹੀ ਵਿੱਚ ਪੂਰੇ ਹੋਏ',
    'Current workload': 'ਮੌਜੂਦਾ ਕੰਮ ਦਾ ਬੋਝ',
    'Healthy': 'ਸਿਹਤਮੰਦ',
    'High': 'ਉੱਚ',
    'Low': 'ਘੱਟ',
    'Verification status': 'ਪੁਸ਼ਟੀਕਰਨ ਸਥਿਤੀ',
    'Verification Pending': 'ਪੁਸ਼ਟੀਕਰਨ ਬਾਕੀ',
    'Jobs completed': 'ਪੂਰੇ ਹੋਏ ਕੰਮ',
    'Avg / job': 'ਔਸਤ / ਕੰਮ',
    'Monthly earnings': 'ਮਹੀਨਾਵਾਰ ਕਮਾਈ',
    'Recent payouts': 'ਹਾਲੀਆ ਭੁਗਤਾਨ',
    'Your Earnings': 'ਤੁਹਾਡੀ ਕਮਾਈ',
    'Cooperative Contribution': 'ਸਹਿਕਾਰੀ ਯੋਗਦਾਨ',
    'Worker Welfare Fund': 'ਕਰਮਚਾਰੀ ਭਲਾਈ ਫੰਡ',
    'You Receive': 'ਤੁਹਾਨੂੰ ਮਿਲਦਾ ਹੈ',
    'My Cooperative Benefits': 'ਮੇਰੇ ਸਹਿਕਾਰੀ ਲਾਭ',
    'Earnings this month': 'ਇਸ ਮਹੀਨੇ ਦੀ ਕਮਾਈ',
    'Welfare contribution': 'ਭਲਾਈ ਯੋਗਦਾਨ',
    'Coop contribution': 'ਸਹਿਕਾਰੀ ਯੋਗਦਾਨ',
    'Total benefits': 'ਕੁੱਲ ਲਾਭ',
    'This year': 'ਇਸ ਸਾਲ',
    'Health Insurance': 'ਸਿਹਤ ਬੀਮਾ',
    'Active': 'ਸਰਗਰਮ',
    'Accident Cover': 'ਦੁਰਘਟਨਾ ਕਵਰ',
    'cover': 'ਕਵਰ',
    'Skill Upgradation': 'ਹੁਨਰ ਸੁਧਾਰ',
    'courses': 'ਕੋਰਸ',
    'Savings Fund': 'ਬੱਚਤ ਫੰਡ',
    'Tool Subsidy': 'ਸੰਦ ਸਬਸਿਡੀ',
    'Up to': 'ਵੱਧ ਤੋਂ ਵੱਧ',
    'Cooperative Voting': 'ਸਹਿਕਾਰੀ ਵੋਟਿੰਗ',
    'Life Insurance': 'ਜੀਵਨ ਬੀਮਾ',
    'Skills': 'ਹੁਨਰ',
    'Certifications': 'ਸਰਟੀਫਿਕੇਟ',
    'Issued by': 'ਜਾਰੀਕਰਤਾ',
    'Availability status': 'ਉਪਲਬਧਤਾ ਸਥਿਤੀ',
    'You are receiving job requests': 'ਤੁਹਾਨੂੰ ਕੰਮ ਦੀਆਂ ਬੇਨਤੀਆਂ ਮਿਲ ਰਹੀਆਂ ਹਨ',
    'You are currently unavailable': 'ਤੁਸੀਂ ਇਸ ਵੇਲੇ ਉਪਲਬਧ ਨਹੀਂ ਹੋ',
    "Today's time slots": 'ਅੱਜ ਦੇ ਸਮੇਂ',
    'Recent jobs (7 days)': 'ਹਾਲੀਆ ਕੰਮ (7 ਦਿਨ)',
    'Service Started': 'ਸੇਵਾ ਸ਼ੁਰੂ',
    'Service Completed': 'ਸੇਵਾ ਪੂਰੀ',
    'Completed': 'ਪੂਰਾ',
    'Rejected': 'ਰੱਦ',
    'Accepted': 'ਸਵੀਕਾਰ',
    'On the Way': 'ਰਾਹ ਵਿੱਚ',
    'Requested': 'ਬੇਨਤੀ ਕੀਤੀ',
    'Rated': 'ਰੇਟ ਕੀਤਾ',
    'Paid': 'ਭੁਗਤਾਨ ਹੋਇਆ',
    'Accept': 'ਸਵੀਕਾਰ ਕਰੋ',
    'Reject': 'ਰੱਦ ਕਰੋ',
    'Advance status': 'ਅਗਲਾ ਪੜਾਅ',
    'Advance to next status': 'ਅਗਲੇ ਪੜਾਅ ਤੇ ਜਾਓ',
    'Total Workers': 'ਕੁੱਲ ਕਰਮਚਾਰੀ',
    'Active Workers': 'ਸਰਗਰਮ ਕਰਮਚਾਰੀ',
    'Verified Workers': 'ਪ੍ਰਮਾਣਿਤ ਕਰਮਚਾਰੀ',
    'Pending Verification': 'ਪੁਸ਼ਟੀਕਰਨ ਬਾਕੀ',
    'Cooperative Revenue': 'ਸਹਿਕਾਰੀ ਆਮਦਨ',
    'Total Welfare Funds': 'ਕੁੱਲ ਭਲਾਈ ਫੰਡ',
    'AI Recommendation': 'ਏਆਈ ਸੁਝਾਅ',
    'Payment & Price Breakdown': 'ਭੁਗਤਾਨ ਅਤੇ ਕੀਮਤ ਵੰਡ',
    'Worker Earnings': 'ਕਰਮਚਾਰੀ ਕਮਾਈ',
    'Cooperative Operations': 'ਸਹਿਕਾਰੀ ਸੰਚਾਲਨ',
    'Total Amount': 'ਕੁੱਲ ਰਕਮ',
    'Payment Method': 'ਭੁਗਤਾਨ ਢੰਗ',
    'UPI': 'ਯੂਪੀਆਈ',
    'Card': 'ਕਾਰਡ',
    'Net Banking': 'ਨੈੱਟ ਬੈਂਕਿੰਗ',
    'Pay & Confirm': 'ਭੁਗਤਾਨ ਕਰੋ ਅਤੇ ਪੁਸ਼ਟੀ ਕਰੋ',
    'Invoice': 'ਚਲਾਨ',
    'Damage Insurance Premium': 'ਨੁਕਸਾਨ ਬੀਮਾ ਪ੍ਰੀਮੀਅਮ',
    'Welfare Fund Contribution': 'ਭਲਾਈ ਫੰਡ ਯੋਗਦਾਨ',
    'Rating Feedback': 'ਰੇਟਿੰਗ ਅਤੇ ਫੀਡਬੈਕ',
    'Complaint': 'ਸ਼ਿਕਾਇਤ',
    '3-Day Warranty': '3-ਦਿਨ ਵਾਰੰਟੀ',
    'Damage Insurance': 'ਨੁਕਸਾਨ ਬੀਮਾ',
    'Submit Rating': 'ਰੇਟਿੰਗ ਦਿਓ',
    'File Complaint': 'ਸ਼ਿਕਾਇਤ ਦਰਜ ਕਰੋ',
    'Claim Warranty': 'ਵਾਰੰਟੀ ਦਾਅਵਾ ਕਰੋ',
    'Claim Insurance': 'ਬੀਮਾ ਦਾਅਵਾ ਕਰੋ',
    'Select skills': 'ਹੁਨਰ ਚੁਣੋ',
    'Choose one or more skills': 'ਇੱਕ ਜਾਂ ਵੱਧ ਹੁਨਰ ਚੁਣੋ',
    'Customer': 'ਗਾਹਕ',
    'Cooperative Worker': 'ਸਹਿਕਾਰੀ ਕਰਮਚਾਰੀ',
    'Login': 'ਲੌਗਇਨ',
    'Sign Up': 'ਸਾਈਨ ਅੱਪ',
    'Mobile or Email': 'ਮੋਬਾਈਲ ਜਾਂ ਈਮੇਲ',
    'Password / OTP': 'ਪਾਸਵਰਡ / ਓਟੀਪੀ',
    'Full Name': 'ਪੂਰਾ ਨਾਮ',
    'Mobile Number': 'ਮੋਬਾਈਲ ਨੰਬਰ',
    'Email (optional)': 'ਈਮੇਲ (ਵਿਕਲਪਿਕ)',
    'Service Details': 'ਸੇਵਾ ਵੇਰਵੇ',
    'Service Category': 'ਸੇਵਾ ਸ਼੍ਰੇਣੀ',
    'Experience (years)': 'ਤਜਰਬਾ (ਸਾਲ)',
    'Service Area': 'ਸੇਵਾ ਖੇਤਰ',
    'Choose a demo role to continue': 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਇੱਕ ਡੈਮੋ ਭੂਮਿਕਾ ਚੁਣੋ',
    'Continue as': 'ਇਸ ਤਰ੍ਹਾਂ ਜਾਰੀ ਰੱਖੋ',
    'Email': 'ਈਮੇਲ',
    'Password': 'ਪਾਸਵਰਡ',
    'Language': 'ਭਾਸ਼ਾ',
    'Match': 'ਮੇਲ',
    'Current Workload': 'ਮੌਜੂਦਾ ਕੰਮ ਦਾ ਬੋਝ',
    'Recent Jobs': 'ਹਾਲੀਆ ਕੰਮ',
    'this week': 'ਇਸ ਹਫ਼ਤੇ',
    'verified': 'ਪ੍ਰਮਾਣਿਤ',
    'Skill relevance': 'ਹੁਨਰ ਪ੍ਰਸੰਗਿਕਤਾ',
    'Distance': 'ਦੂਰੀ',
    'Experience': 'ਤਜਰਬਾ',
    'Dispatch Worker': 'ਕਰਮਚਾਰੀ ਭੇਜੋ',
    'Select': 'ਚੁਣੋ',
    'View Profile': 'ਪ੍ਰੋਫਾਈਲ ਵੇਖੋ',
    'Hide profile': 'ਪ੍ਰੋਫਾਈਲ ਲੁਕਾਓ',
    'About': 'ਜਾਣ-ਪਛਾਣ',
    'Jobs Completed': 'ਪੂਰੇ ਹੋਏ ਕੰਮ',
    'Avg Rating': 'ਔਸਤ ਰੇਟਿੰਗ',
    'Demand across areas': 'ਖੇਤਰਾਂ ਵਿੱਚ ਮੰਗ',
    'Househelp': 'ਘਰੇਲੂ ਸਹਾਇਤਾ',
    'Cooking, dusting, daily chores': 'ਖਾਣਾ ਬਣਾਉਣਾ, ਸਫਾਈ, ਰੋਜ਼ ਦੇ ਕੰਮ',
  },
};
